#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rails-html-sanitizer
Version  : 1.0.3
Release  : 6
URL      : https://rubygems.org/downloads/rails-html-sanitizer-1.0.3.gem
Source0  : https://rubygems.org/downloads/rails-html-sanitizer-1.0.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rails-dom-testing
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Rails Html Sanitizers
In Rails 4.2 and above this gem will be responsible for sanitizing HTML fragments in Rails
applications, i.e. in the `sanitize`, `sanitize_css`, `strip_tags` and `strip_links` methods.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rails-html-sanitizer-1.0.3
gem spec %{SOURCE0} -l --ruby > rubygem-rails-html-sanitizer.gemspec

%build
gem build rubygem-rails-html-sanitizer.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rails-html-sanitizer-1.0.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rails-html-sanitizer-1.0.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/lib/rails-html-sanitizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/lib/rails/html/sanitizer.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/lib/rails/html/sanitizer/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/lib/rails/html/scrubbers.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/test/sanitizer_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/rails-html-sanitizer-1.0.3/test/scrubbers_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rails-html-sanitizer-1.0.3.gemspec
